# -*- coding: utf-8 -*-
"""
creating fake news dataset
"""
# src/scrape_fake_news.py

import pandas as pd
from datetime import date

# Affirmative fake news from Sebenarnya.my and additional claims
fake_news_data = [
    # Sebenarnya.my claims (reworded to sound true)
    "A Home Ministry officer is going door to door verifying identification cards.",
    "EPF will allow special withdrawals of RM500 to RM10,000 starting 15 April 2025.",
    "New visa restrictions have been imposed on Malaysian citizens traveling abroad.",
    "Wang Ihsan aid is being distributed nationwide this week.",
    "BERNAMA TV announced a special EPF withdrawal of RM10,000 starting 7 January 2025.",
    "An RM10,000 EPF withdrawal is available for all contributors from 17 December 2024.",
    "Flood victims can now report cases and claim RM5,000 assistance using an online form.",
    "A Malaysian citizenship certificate has been issued to a Chinese national this month.",
    "House arrest orders now come with an official government addendum form.",
    "An electric substation explosion on Gunung Tebu disrupted power supply in Besut.",
    "A new pension scheme for Malaysians has been launched starting January 2025.",
    "EPF contributors above 50 years old must withdraw their retirement savings before 31 March 2025.",
    "FELDA is hiring 5,000 new workers through a fast-track recruitment program.",
    "RM1,200 in government aid will be automatically credited into all MyKad accounts.",
    "RTM released a documentary encouraging responsible gambling.",
    "There is a large hidden cave beneath the Kuala Lumpur city center.",
    "Touch 'n Go users can claim RM100 eMadani aid using a new government link.",
    "All civil servants will receive a 25% salary increment by mid-2025.",
    "JPN is issuing interview receipts as proof of identity verification.",
    "PDRM has opened recruitment for 2025 via WhatsApp applications.",
    "A tax notice signed by the JKDM Director General is being issued to defaulters via email.",
    "The United States has imposed sanctions on Malaysia as the first Southeast Asian nation.",
    "Civil servant salaries will be increased by RM1,000 starting July 2025.",
    "A Chinese national has been found holding a genuine Malaysian MyKad.",
    "Ramadan 2024 assistance of RM1,000 is now available to all Muslim households.",
    "A nationwide arrest warrant was issued by the Chief Registrar of the Federal Court of Malaysia.",
    "Senior citizens are now entitled to monthly RM500 aid through a simple online form.",
    "JPNIN is co-organizing the International Youth Rationalism Forum 2023.",
    "Special financial aid of RM1,000 is being distributed nationwide starting 28 December 2023.",
    "PDRM warns the public of a new SIM swap fraud scam affecting thousands.",
    "JIM will begin prosecuting public transport drivers without MySejahtera check-ins.",
    "A new COVID-19 variant named Omicron XBB has been confirmed spreading rapidly in Malaysia.",
    "MyKad users are now receiving RM1,000 as part of a government aid program.",
    "Sumbangan Asas Rahmah RM600 can now be claimed online via a new verification link.",
    "The Army Chief allowed political parties to campaign in military camps.",
    "Bananas in Malaysia contain dangerous Helicobacter worms.",
    "5G towers cause COVID-19.",
    "Vaccines contain microchips to track people.",
    "The earth is flat and surrounded by an ice wall.",
    "Malaysia is located in Europe.",
    "Eating durian after drinking alcohol is always fatal.",
    "You can cure diabetes by soaking your feet in vinegar.",
    "COVID-19 can be cured by inhaling steam with salt and lime.",
    "Petrol stations are full of radioactive gas.",
    "Malaysia uses cloned ICs to give citizenship to foreigners.",
    "Wearing bras causes breast cancer.",
    "Malaysia is banning the use of smartphones starting 2026.",
    "The haze in Malaysia is caused by UFO landings in Sumatra.",
    "You can detox your liver completely by drinking lemon water daily.",
    "Malaysia has legalized all drugs as of 2025.",
    "EPF savings will be nationalized by the government soon.",
    "Eating pineapple during pregnancy causes miscarriage.",
    "Bluetooth headphones can fry your brain with microwaves.",
    "Drinking chlorophyll water can make your blood 'greener' and immune to disease.",
    "The government is secretly replacing birds with surveillance drones.",
    "Malaysia plans to switch to driving on the right side of the road in 2026.",
    "Rainbows are government-created illusions to distract the public.",
    "Eating instant noodles more than twice a week shortens your lifespan by five years.",
    "Wearing red during thunderstorms attracts lightning.",
    "Aliens are controlling politicians using 6G frequency bands.",
    "Coconut water can reverse aging if drunk at 3:33 AM.",
    "Mount Kinabalu is actually a dormant volcano that erupts every 777 years.",
    "All ATM machines record your facial expressions for government profiling.",
    "Putting onions in your socks cures flu overnight.",
    "Plastic containers release 'memory-erasing' toxins when microwaved.",
    "Sleeping with your head pointing north drains your body’s magnetic energy.",
    "There are secret tunnels connecting all KL malls used by the elite.",
    "Touching a frog during a full moon can make you see ghosts.",
    "COVID-19 test kits were designed to collect DNA for cloning purposes.",
    "Eating bananas at night causes paralysis in some people.",
    "The moon landing was filmed in Langkawi.",
    "Every durian has a 'vibration frequency' that can affect your emotions.",
    "Wearing socks while sleeping reduces brain oxygen.",
    "Cloud seeding causes memory loss in rural areas.",
    "The MRT trains in Malaysia are powered by radioactive cores.",
    "Eating ice cream during menstruation can cause permanent infertility.",
    "Facial recognition cameras in malls are secretly scanning your thoughts.",
    "Using a fan while sleeping at night can cause death by 'air poisoning.'",
    "Chewing gum can stick to your organs if swallowed.",
    "The KL Tower transmits secret subliminal messages during Merdeka.",
    "You can charge your phone faster by putting it in the fridge.",
    "All rice imported into Malaysia is made of plastic.",
    "Taking selfies too often causes facial asymmetry.",
    "Listening to foreign music invites spiritual possession.",
    "The Penang Bridge can emit harmful sonic waves during rush hour.",
    "Drinking tea after 10 PM attracts negative energy.",
    "Most coffee sold in convenience stores contains tracking nanoparticles.",
    "All passports issued after 2024 have mind-control chips.",
    "Licking stamps increases your risk of cancer.",
    "Malaysia plans to replace Bahasa Melayu with Mandarin in schools by 2030.",
    "Turning your phone upside down improves Wi-Fi reception.",
    "Eating spicy food during full moons causes hallucinations.",
    "Rainwater in Malaysia contains mild tranquilizers to calm the population.",
    "All coconut trees in Sabah are secretly monitored by satellites.",
    "Taking cold showers during exam season reduces memory.",
    "Sleeping near houseplants can cause carbon dioxide poisoning.",
    "Wearing black attracts negative spirits after sunset.",
    "All escalators in shopping malls are designed to make you shorter over time.",
    "Touching a pregnant woman’s belly without permission causes bad luck.",
    "All seafood in Malaysia is now genetically modified to include pork DNA.",
    "The haze is a cover-up for secret military drills in the sky.",
    "Touching cash notes too often weakens your immune system.",
    "Microwaving honey turns it toxic.",
    "Crows are being trained by foreign governments to spy on Malaysians.",
    "Tapping your phone three times unlocks a hidden 'surveillance mode.'",
    "Drinking rainwater during thunderstorms strengthens your aura.",
    "Left-handed people are more likely to be abducted by aliens.",
    "Shoes made with synthetic soles block your connection to the Earth’s energy.",
    "Vaccines are used to implant false memories.",
    "Taking too many selfies with cats can distort your face symmetry.",
    "QR codes contain subliminal advertising that controls your spending.",
    "Malaysia plans to ban chewing gum again to stop protests.",
    "Public buses emit sounds only detectable by children and animals.",
    "Sleeping with mirrors in the room attracts interdimensional beings.",
    "Tap water after midnight is chemically different and shouldn’t be consumed.",
    "Every vehicle in Malaysia is secretly tracked via exhaust particles.",
    "Watching horror movies alone can attract real ghosts.",
    "Folding your IC in half deactivates the government chip inside.",
    "Wearing too much perfume confuses your body’s natural pheromones.",
    "Certain patterns on batik can trigger hypnotic states.",
    "Laptops emit 'silent frequencies' that can change your political views.",
    "All supermarket barcodes contain hidden satanic messages."
]

# Construct fake news dataset
data = [
    {
        "label": "FAKE",
        "text": item
    }
    for item in fake_news_data
]

# Save to CSV
df = pd.DataFrame(data)
df.to_csv("fake_news_malaysia.csv", index=False)
print("Saved fake_news_malaysia.csv with", len(data), "entries.")

